#!/bin/sh
# See the river(1), riverctl(1), and rivertile(1) man pages for complete docs.

waybar -c ~/.config/waybar/config_river &
swaybg -i ~/Pictures/Wallpapers/misbehaving.jpg &
eww daemon &
dunst &
# kanshi &

# Start foot in tiled or floating mode
riverctl map normal Super Return spawn 'foot'
riverctl map normal Super+Shift Return spawn 'foot -a floatyFoot'

# Rofi + Eww
riverctl map normal Super D spawn 'rofi -show drun'
riverctl map normal Super E spawn 'eww -c ~/.config/eww/ctrl/ open dash --toggle'

# Screenshots
riverctl map normal Super P spawn 'grim -g "$(slurp)" - | wl-copy && wl-paste > ~/Screenshots/$(date +%F_%T).png'
riverctl map normal Super+Shift P spawn 'grim - | wl-copy && wl-paste > ~/Screenshots/$(date +%F_%T)_full.png'

# Common Software
riverctl map normal Super W spawn 'thunar'
riverctl map normal Super B spawn 'firefox'
riverctl map normal Super V spawn 'code'

# Super+Q to close the focused window
riverctl map normal Super Q close

# Super+Shift+Q to exit river
riverctl map normal Super+Shift Q exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the active window with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous display
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the active window to the next/previous display
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the active window to the top of the layout stack
# swap with highest master
riverctl map normal Super+Control Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
# increment/decrement number of masters in rivertile
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    # move to tag i
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag active window with tag [0-8]
    # send to tag 1
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of active window
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
# Super+0 to focus all tags
# i.e show all windows of all tags
riverctl map normal Super 0 set-focused-tags $all_tags
# Super+Shift+0 to tag active window with all tags
# i.e show current window on all tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
# master t/r/b/l
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough
# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough
# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'amixer sset Master 1%+'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'amixer sset Master 1%-'
    riverctl map $mode None XF86AudioMute         spawn 'amixer sset Master toggle'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'
done

# Set backuround and border color
riverctl background-color 0x211d13
riverctl border-color-focused 0xdb930d
riverctl border-color-unfocused 0x3a3124

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
# THE FOLLOWING WILL BE IMPLEMENTED IN RIVER 0.3, REMOVE COMMENTS THEN
# riverctl rule-add float -app-id 'float*' -title 'foo'
# riverctl rule-add float -app-id 'Spotify'
# riverctl rule-add float -app-id 'floatyFoot'

# REMOVE THESE WHEN RIVER 0.3 COMES OUT
riverctl float-filter-add app-id "floatyFoot"
riverctl float-filter-add app-id "Spotify"

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add csd -app-id "bar"

riverctl attach-mode bottom
riverctl border-width 6
riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-output-change

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 5 -outer-padding 5 -main-ratio 0.52 &
