#!/bin/bash

# Set decoration geometry
berryc border_width 20
berryc inner_border_width 2
berryc title_height 0
berryc edge_gap 48 10 10 10

# Set decoration colors
berryc focus_color 161616
berryc unfocus_color 161616
berryc inner_focus_color EE5396
berryc inner_unfocus_color F2F4F8

# Other options
berryc smart_place "true"
berryc draw_text   "false"

sxhkd -c $HOME/.config/berry/sxhkdrc &
nitrogen --restore &
polybar -c $HOME/.config/berry/config.ini main
