initial_screen = "library"
use_nerdfont = true
notify = true
gapless = true
flip_status_indicators=true
shuffle = false
repeat = 'off'
hide_display_names = true
cover = true
share_clipboard = true

[theme]
background = "#f2e5bc"
primary = "#282828"
secondary = "#3c3836"
title = "#d79921"
playing = "#3c3836"
playing_selected = "#98971a"
playing_bg = "#98971a"
highlight = "#98971a"
highlight_bg = "#3c3836"
error = "#f2e5bc"
error_bg = "#cc241d"
statusbar = "#ebdbb2"
statusbar_progress = "#d79921"
statusbar_bg = "#458588"
cmdline = "#f9f5d7"
cmdline_bg = "#076679"
