#!/bin/bash

# Set decoration geometry
berryc border_width 2
berryc inner_border_width 4
berryc title_height 40
berryc edge_gap 13 13 106 13

# Text
berryc draw_text "true"
berryc set_font "ComicShannsMono Nerd Font-9"

# Set decoration colors
berryc focus_color         191724
berryc unfocus_color       191724
berryc inner_focus_color   9ccfd8
berryc inner_unfocus_color 6e6a86 

# Other options
berryc smart_place "true"
berryc focus_follows_pointer "false"

# Desktop names
berryc name_desktop 0 "a"
berryc name_desktop 1 "b"
berryc name_desktop 2 "c"
berryc name_desktop 3 "d"
berryc name_desktop 4 "e"
berryc name_desktop 5 "f"
berryc name_desktop 6 "g"
berryc name_desktop 7 "h"
berryc name_desktop 8 "i"
berryc name_desktop 9 "j"

# Start sxhkd and other programs
sxhkd -c $HOME/.config/berry/sxhkdrc &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
xset s 480 dpms 600 600 600 &
/usr/lib/polkit-1/polkit-d &
dunst
