#!/bin/bash

cacheDir="$HOME/.config/eww/dash/scripts/cache/"

updatequotes() {
  uri=$(curl -s "https://api.quotable.io/random?maxLength=110")
  echo $uri | jq '.content' |  cut -d "\"" -f 2 > "${cacheDir}quote"
  echo $uri | jq '.author' |  cut -d "\"" -f 2 > "${cacheDir}author"
}

quote=$(cat ${cacheDir}quote)
author=$(cat ${cacheDir}author)

case $1 in
  quote)
    echo $quote
    ;;
  author)
    echo $author
    ;;
  update)
    updatequotes
    ;;
esac
