#!/bin/bash

# Battery
get_bat(){
	upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | awk '{print $2}' | cut -d '.' -f1
}

# Brightness
get_bright(){
	brightnessctl -m -d acpi_video0 | awk -F, '{print substr($4, 0, length($4)-1)}' | tr -d '%'
}

# Volume
get_vol(){
	amixer -D pulse sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%'
}

# Uptime
get_uptime(){
	uptime -p | cut -d ' ' -f2-
}

# Execute accordingly
if [[ "$1" == "bat" ]]; then
	get_bat
elif [[ "$1" == "bri" ]]; then
	get_bright
elif [[ "$1" == "vol" ]]; then
	get_vol
elif [[ "$1" == "upt" ]]; then
	get_uptime
fi
