#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & nitrogen --restore & ~/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         5
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true

bspc config focused_border_color "#ee5396"
bspc config normal_border_color "#161616"

bspc rule -a Code desktop = '^1'
bspc rule -a firefox desktop = '^2'
bspc rule -a discord desktop = '^4'

