#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & nitrogen --restore & polybar -c /etc/polybar/config.ini

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         5
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^2'
