#!/bin/bash

icon() {
    if [[ $2 == "no" ]]; then
        echo "󰋋"
    else
        echo "󰝟"
    fi
}

vol=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '[0-9]{1,3}(?=%)' | head -1)
muted=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
icon=$(icon "$vol" "$muted")

if [[ $1  == "--get" ]]; then
    pactl subscribe | grep --line-buffered "on sink" | while read -r _ ; do
            vol=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '[0-9]{1,3}(?=%)' | head -1)
            muted=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
            icon=$(icon "$vol" "$muted")
            echo "{\"icon\": \"$icon\", \"value\": \"$vol\"}"
    done

elif [[ $1 == "--set" ]]; then

    if (( $2 >= 0 && $2 <= 100 )); then
        pactl set-sink-volume @DEFAULT_SINK@ $2%
    fi

elif [[ $1 == "--toggle" ]]; then
        pactl set-sink-mute @DEFAULT_SINK@ toggle
        muted=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
        vol=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '[0-9]{1,3}(?=%)' | head -1)
        icon=$(icon "$vol" "$muted")
fi
