[theme]
background = "#fdf6e3"
primary = "#5c6a72"
secondary = "#efebd4"
title = "#35a77c"
playing = "#efebd4"
playing_selected = "#8da101"
playing_bg = "#8da101"
highlight = "#8da101"
highlight_bg = "#343f44"
error = "#2d353b"
error_bg = "#F85552"
statusbar = "#2d353b"
statusbar_progress = "#DFA000"
statusbar_bg = "#35a77c"
cmdline = "#525252"
cmdline_bg = "#93b259"