[theme]
background = "#161616"
primary = "#ffffff"
secondary = "#f2f4df8"
title = "#78a9ff"
playing = "#f2f4f8"
playing_selected = "#ee5396"
playing_bg = "#ee5396"
highlight = "#ee5396"
highlight_bg = "#262626"
error = "#262626"
error_bg = "#be95ff"
statusbar = "#393939"
statusbar_progress = "#78a9ff"
statusbar_bg = "#08bdba"
cmdline = "#525252"
cmdline_bg = "#3ddbd9"
