theme = "swamp"
client_id = ""
client_port = 8080
playback_format = """
{track} • {artists}
{album}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "<3"
border_type = "Hidden"
progress_bar_type = "Rectangle"
playback_window_position = "Bottom"
playback_window_width = 3
enable_media_control = true
enable_streaming = "Always"
enable_notify = true
enable_cover_image_cache = true
default_device = "sharktooth"
notify_streaming_only = false

[copy_command]
command = "xclip"
args = [
    "-sel",
    "c",
]

[notify_format]
summary = "{track} • {artists}"
body = "{album}"

[device]
name = "sharktooth"
device_type = "computer"
volume = 75
bitrate = 320
audio_cache = false
normalization = false
