#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
xset s 480 dpms 600 600 600 &
/usr/lib/polkit-1/polkitd &
nitrogen --restore &
dunst &

bspc monitor -d I II III IV V VI VII VII XI X

normal="#6e6a86"
accent="#9ccfd8"

bspc config presel_feedback_color $accent
bspc config focused_border_color $accent
bspc config normal_border_color $normal

bspc config border_width         4
bspc config window_gap          12
bspc config top_padding         78

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Code desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a Spotify desktop='^3' #https://github.com/MujtabaAsim/Misc/blob/main/spotify_player.desktop
bspc rule -a discord desktop='^4'
bspc rule -a Gthumb desktop='^5'

bspc rule -a feh state=floating
bspc rule -a Cpupower-gui state=floating
bspc rule -a Lxappearance state=floating