#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
xset s 480 dpms 600 600 600 &
/usr/lib/polkit-1/polkitd &
eww open topbar &
~/.fehbg &
dunst &

bspc monitor -d 1 2 3 4 5 6 7
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10
# bspc monitor -d i ii iii iv v vi vii viii ix x
# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d 0000 0001 0010 0011 0100 0101 0110 0111 1000
# bspc monitor -d sin cos tan csc sec cot deg rad

normal="#3a3124"
accent="#db930d"

bspc config presel_feedback_color $accent
bspc config focused_border_color $accent
bspc config normal_border_color $normal 

bspc config border_width        4
bspc config window_gap          8
bspc config bottom_padding      72

bspc config split_ratio          0.5

bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true

bspc config focus_follows_pointer true
bspc config pointer_modifier    mod4
bspc config pointer_action1     resize_corner

bspc rule -a Code desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a Spotify desktop='^3' 
bspc rule -a discord desktop='^4'
bspc rule -a Gthumb desktop='^5'

bspc rule -a feh state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Cpupower-gui state=floating
bspc rule -a Lxappearance state=floati
