#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
xset s 480 dpms 600 600 600 &
xset r rate 300 50
/usr/lib/polkit-1/polkitd &
# eww open-many bar:b1 --arg b1:x=5 --arg b1:w=118 --arg b1:widget_name=wspBar bar:b2 --arg b2:x=128 --arg b2:w=214 --arg b2:widget_name=timeBar bar:b3 --arg b3:x=347 --arg b3:w=133 --arg b3:widget_name=musicBar
eww open topbar
# $HOME/.config/polybar/launch.sh &
~/.fehbg &
# feh --bg-fill --randomize ~/Pictures/Wallpapers/* &
dunst &

bspc monitor -d 1 2 3 4 5 6 7 8 9
# bspc monitor -d 1 2 3 4 5 6 7
# bspc monitor -d 1 2 3 4 5 6
# bspc monitor -d 1 2 3 4 5
# bspc monitor -d 0000 0001 0010 0011 0100 0101 0110 0111 1000

normal="#3a3124"
accent="#db930d"

bspc config presel_feedback_color $accent
bspc config focused_border_color $accent
bspc config normal_border_color $normal 

bspc config border_width        4
bspc config window_gap          10
bspc config split_ratio          0.5

bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true

bspc config focus_follows_pointer true
bspc config pointer_modifier      mod4
bspc config pointer_action1       resize_corner

bspc rule -a Code desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a Spotify desktop='^3' 
bspc rule -a discord desktop='^4'
bspc rule -a Gthumb desktop='^5'
bspc rule -a Syncthing desktop='^5'

bspc rule -a feh state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Cpupower-gui state=floating
bspc rule -a Lxappearance state=floating