#!/bin/bash

# Set decoration geometry
berryc border_width 10
berryc inner_border_width 4
berryc title_height 0
berryc edge_gap 20 85 20 20

# Set decoration colors
berryc focus_color fdf6e3 
berryc unfocus_color fdf6e3
berryc inner_focus_color 8da101
berryc inner_unfocus_color 5c6a72

# Other options
berryc smart_place "true"
berryc draw_text   "false"

sxhkd -c $HOME/.config/berry/sxhkdrc &
nitrogen --restore &
$HOME/.config/polybar/launch.sh
